version: '3'

tasks:
  run:
    desc: Run todo locally
    cmd: go run ./cmd/todo
  build:
    desc: Build todo locally
    cmd: go build -o bin/todo ./cmd/todo
  tidy:
    desc: Add missing and remove unused modules
    cmd: go mod tidy
